[package]
name = "live777"
version = "0.3.3"
edition = "2021"
license = "MPL-2.0"
description = "A very simple, high performance, edge WebRTC SFU"

[workspace]
members = [".", "libs/cli", "libs/libwish", "tools/whepfrom", "tools/whipinto"]

[dependencies]
axum = { version = "0.6.20", features = ["multipart"] }
tower-http = { version = "0.4.3", features = ["fs", "auth"] }

# TODO
# There have error, Next commit can't work with obs studio
# webrtc = { git = "https://github.com/webrtc-rs/webrtc", rev = "9c0570ad562b226cc9c6c0a3c7a9a28e1d43e08f" }
# Reference: https://github.com/binbat/live777/issues/39
webrtc = { git = "https://github.com/webrtc-rs/webrtc", rev = "3f34e2e055463e88f5e68ef09f98f9c5c674ff42" }
anyhow = "1.0"
tokio = { version = "1.30", features = ["full"] }
hyper = "0.14"
log = "0.4.20"
env_logger = "0.10.0"
serde = { version = "1.0.188", features = ["serde_derive"] }
toml = "0.7.6"
serde_json = "1.0.105"
http = "0.2.9"
http-body = "0.4.5"
base64 = "0.21.3"
mime_guess = "2.0.4"
rust-embed = { version = "8.0.0", features = ["axum-ex"] }
prometheus = "0.13.3"
lazy_static = "1.4.0"
thiserror = "1"

# cargo install cargo-deb
# Reference:  https://github.com/kornelski/cargo-deb
[package.metadata.deb]
maintainer = "Metal A-Wing <1@233.email>"
copyright = "BinBat LTD <hey@binbat.com>"
license-file = ["LICENSE"]
extended-description = """\
A very simple, high performance, edge WebRTC SFU.\
Real-time video streaming for the `WHIP`/`WHEP` as first protocol.\
"""
depends = "libc6 systemd"
section = "utility"
priority = "optional"
assets = [
    ["target/release/live777", "usr/bin/", "755"],
    ["target/release/whipinto", "usr/bin/", "755"],
    ["target/release/whepfrom", "usr/bin/", "755"],
    ["config-dist.toml", "etc/live777/config.toml", "644"],
    ["live777.service", "usr/lib/systemd/system/live777.service", "644"],
    ["README.md", "usr/share/doc/live777/README", "644"],
]
