[package]
name = "live777"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "libs/whip-whep", "libs/cli", "rtp2whip", "whep2rtp"]

[dependencies]
axum = { version = "0.6.20", features = ["multipart"] }
tower-http = { version = "0.4.3", features = ["fs", "auth"] }
webrtc = { git = "https://github.com/webrtc-rs/webrtc" }
anyhow = "1.0"
tokio = { version = "1.30", features = ["full"] }
hyper = "0.14"
log = "0.4.20"
env_logger = "0.10.0"
serde = { version = "1.0.188", features = ["serde_derive"] }
toml = "0.7.6"
serde_json = "1.0.105"
rand = "0.8.5"
http = "0.2.9"
http-body = "0.4.5"
base64 = "0.21.3"
mime_guess = "2.0.4"
rust-embed = { version = "8.0.0", features = ["axum-ex"] }
